spring.application.name=payment-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5433/nearbuy_db
spring.datasource.username=postgres
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update