spring.application.name=listing-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/nearbuy_db
spring.datasource.username=postgres
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update