spring.application.name=chat-service
server.port=${SERVER_PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/nearbuy_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:yourpassword}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
listing-service.url=${LISTING_SERVICE_URL:http://localhost:8082}
user-service.url=${USER_SERVICE_URL:http://localhost:8081}
